### ISSUE TITLE
Restoring the VOD payback position obsolete?

### ISSUE THREAD

**Issue by fabd** [EhsanKia/TwitchPlayerPlus#12]
According to [a Reddit thread](https://www.reddit.com/r/Twitch/comments/4yq900/til_if_you_leave_a_stream_and_then_watch_the_past/) "VODs remember playback position" now.

VOD position is restored in a VOD I watched recently. Appears to work (with this script disabled just to be sure :D ). Interestingly thread claims that this works also from live to vod.

It connects to: https://api.twitch.tv/api/resumewatching/user-video?id=__________ at regular intervals.

What isn't clear is their implementation. How many VODs are remembered, etc.

Just a heads up.

**Comment by EhsanKia** [comment]
Yeah, they've been slowly rolling it out. I've had it for over a month now. Theirs is even better because if you're watching the live stream, stop, then watch the VOD, it takes you to the right place too. I'll remove the code when I get some free time.

**Comment by fabd** [comment]
You know what? It's unreliable enough that it renders their implementation nearly useless for me.

I think it might be useful to have this feature as a backup. Perhaps if we can detect that they are seeking past the start position when they load a stream?

This is the same issue I have with YouTube. It is unreliable. God knows why sometimes it restores a video that I was halfway through, other times it doesn't.

This add on has limitations, but at least it was reliable. Anyway just my input on it.

**Comment by fabd** [comment]
Bah. It is not obsolete any time soon it seems. It's already stopped working for me. I can't find the "resumewatching" URL in the developer console's XHR tab either.

I think it might be worth keeping this feature and perhaps just disable it if the VOD actually resumes. At least in this addon the feature was reliable... >_>

You'd think it is out of testing? They clearly described the "resume" feature in the last iOS updates. And yet, it only worked a few days for me.
