### ISSUE TITLE
Features not working

### ISSUE THREAD

**Issue by IndubitablyBengt** [EhsanKia/TwitchPlayerPlus#13]
The only thing that appears to change is the volume bar always showing, none of the other features appear.

**Comment by EhsanKia** [comment]
Yeah there was a big update to the Twitch player and it broke most features. Will fix soon!

**Comment by EhsanKia** [comment]
Should all be fixed and working now.

**Comment by a13ph** [comment]
@ehsankia For me, on linux Developer Edition Firefox + BTTV I only get always-on volume bar and I don't have no quality selection anywhere.
That's step back, not forward towards one-button-per-quality dream of mine :laughing:

**Comment by EhsanKia** [comment]
Sorry the extension broke again, I'll fix it soon!

**Comment by EhsanKia** [comment]
@a13ph should be fixed now.
