### ISSUE TITLE
Help for new layout

### ISSUE THREAD

**Issue by steven7851** [EhsanKia/TwitchPlayerPlus#15]
In line: ```playerService = App.__container__.lookup('service:persistent-player');```
console return ```Uncaught ReferenceError: App is not defined```

Is it change name or something else?

**Comment by EhsanKia** [comment]
Hmm, I might deprecate this script, unfortunately.

Twitch recently pushed a huge rewrite of the site (which breaks this). Not only that, but the majority of the features from this are now supported natively, so this isn't as needed anymore.

Sadly, unless someone else wants to rewrite it, I don't really have the time to maintain it.
