### ISSUE TITLE
Cleaning up edge cases & public release

### ISSUE THREAD

**Issue by EhsanKia** [EhsanKia/TwitchPlayerPlus#7]
So I've been trying to find more edge cases lately. Some features still break when stream loads after you the page load, or when a second player gets added from hosting. For the latter, injected styles would still apply, but DOM manipulations would need to be redone. Not sure how important that is though. Have you guys found more cases where things break down?

Once this gets slightly more polished, I think we should make a post on /r/Twitch and other places to get the word out. It's starting to become a nice little script that many will find useful. In the process we'll hopefully get more people aboard for testing, feature suggestion and contributions.

**Comment by tduva** [comment]
I encountered something where when I have the quality set to something other than Source (so it applies to any new streams I open), then I load a stream without quality options, which then gets quality options while I have it open, the quality was displayed as Source even though it was e.g. Medium.

I'm not sure if that is a problem with the modifications or of the player itself, but it's a bit difficult to test. I tried opening the cog menu to test if it would set it once you open it, but our modified quality selection didn't change to the correct value. I haven't yet had a chance to test it with and without modifications. What makes it even harder to test is that sometimes the player won't switch to quality options mid-stream on it's own, so I have to reload which is not what I want to test. That's just like opening a stream with quality options which displays correctly.

**Comment by EhsanKia** [comment]
That does sound like a really hard to test edge case. Would definitely be interested to know the default player handles it, I wouldn't be surprised if the issue exists there too.

I just added video seeking and made the stats loading slightly more robust. Also, moving the Volume CSS to the style sheet means that it'll work on all players no matter when and how they are loaded.

I think we're pretty close to a decent 1.0 release.

**Comment by EhsanKia** [comment]
The current implementation saves every 10s, and saves each VOD to a new key. I'm not sure about the long term impact of this, since they never get cleaned up. I was considering using some sort LRU array where I only keep the X most recent vod positions, and store the whole thing under one key.

**Comment by fabd** [comment]
Oh you are implementing the "remember last played position" thingy? Nice! **edit** I tried it now, great feature!

Yes, we're looking at several hours long VODs in most cases, and even on YouTube I hardly ever have the time to finish episodes of just one hour. So the number of seek to remember is small. On the other hand one problem is when you just check out a bunch of VODs.. then with a simple rotation the ones that you actually meant to return to are going to be lost.

With a not too low store like 50 slots it is unlikely a typical user will check so many VODs that the ones they meant to come back to will have been rotated out of the "50 slot" store. In that case I'd say 10 is definitely too low. I'd go for something like 30 to 50 if you want to put a limit.

Another option would be to _not_ store a key if the stream has been playing for less than 1-2 minutes. This would help not losing the play time from VODs you actually meant to come back to, when checking out VODs from new channels. So if eg. I check a VOD from a new channel, and I seek in the middle, and I watch for 40 seconds.. then it won't store that.

**Comment by EhsanKia** [comment]
Honestly, any finite amount is fine. I'm just thinking of the really long term effects, when there'd be thousands of values. I'd probably go with 100. I do agree that having a time limit would also help prune a lot of values.

**Comment by tduva** [comment]
The usage of `flashBackend` breaks the script on Firefox. It says it is undefined.

**Comment by EhsanKia** [comment]
This is quite annoying. flashBackend itself is fine, but for some reason, you can't call functions on flash objects? Works fine in Chrome though. I'll try searching around for solutions, submitted a temporary patch for now that let's the script run through to the end.

**Comment by EhsanKia** [comment]
Finally got around fixing the Firefox issue, and fixed another small bug.
I made the version 1.0, I think it's as clean as it gets for now.

I think if I ever was to make a big refactor, it'd be to scan and apply fixes to any player on the page, rather than focusing only on the first player we detect. This way, we could detect new players being added such as Hosted channels. But for now, that's a small subcase.

**Comment by tduva** [comment]
The usage of `flashBackend` doesn't work with the standalone player URL: `http://player.twitch.tv/?channel=<channel>`

**Comment by EhsanKia** [comment]
That standalone player is where they test their latest code though, so it's fair to assume it'll change very often. I believe there's a way to make that player go 100% HTML5, although I'm not sure how the support is, last I tried it, it was very broken on Chrome.

I put a fix for this one, just chose a more robust selector, hopefully.
